### ISSUE TITLE
Path string cannot be empty Missing `fromPath` parameter

### ISSUE THREAD

**Issue by sajjadasaf** [KevinMenden/hybrid-assembly#1]
I tried to use docker version but it shows the following error. Could you kindly help me to solve this.

Thank you

nextflow run kevinmenden/hybrid-assembly -profile docker --reads '/media/laptop/DBG2OLC-master/Pacbio.fasta'
N E X T F L O W  ~  version 20.10.0
Launching `kevinmenden/hybrid-assembly` [exotic_leakey] - revision: c2aef5f047 [master]
Path string cannot be empty
Missing `fromPath` parameter

**Comment by KevinMenden** [comment]
You'll need to specificy both short and long reads, as it is a hybrid-assembly pipeline. See this command:

`nextflow run kevinmenden/hybrid-assembly --shortReads '*_R{1,2}.fastq.gz' --longReads long_reads.fastq.gz --assembler spades
 -profile docker`

You find a better description in the docs 
https://github.com/KevinMenden/hybrid-assembly/blob/master/docs/usage.md

**Comment by sajjadasaf** [comment]
Thank you very much for your reply. problem solved.
Thank you again for such a nice software.
